# 企业微信开发
## 微信公众号获取access_token
GET https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid={{wx_qy_corpid}}&corpsecret={{wx_qy_app_secret}}
Accept: application/json

> {% client.global.set("access_token", response.body.access_token); %}

### 获取部门列表
GET https://qyapi.weixin.qq.com/cgi-bin/department/list?access_token={{access_token}}
Accept: application/json

> {% client.global.set("department_id", response.body.department[0].id); %}

### 随便发起一个请求。设置departMent_id
GET {{sui_bian}}
Accept: application/json

> {% client.global.set("department_id", "222"); %}

### 查看部门人员列表
GET https://qyapi.weixin.qq.com/cgi-bin/user/simplelist?access_token={{access_token}}&department_id={{department_id}}&fetch_child=FETCH_CHILD
Accept: application/json

### 发送消息
POST https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token={{access_token}}
Content-Type: application/json

{
  "touser" : "youfang",
  "toparty" : null,
  "totag" : null,
  "msgtype" : "textcard",
  "agentid" : 1000003,
  "textcard" : {
    "title" : "领奖通知",
    "description" : "<div class=\"gray\">2016年9月26日</div> <div class=\"normal\">恭喜你抽中iPhone 7一台，领奖码：xxxx</div><div class=\"highlight\">请于2016年10月10日前联系行政同事领取</div>",
    "url" : "URL",
    "btntxt":"更多"
  },
  "enable_id_trans": 0,
  "enable_duplicate_check": 0,
  "duplicate_check_interval": 1800
}